### ISSUE TITLE
Serial needs a pattern.

### ISSUE THREAD

**Issue by CheezBoiger** [MichaelWallace30/CommProtocol#13]
As already said to me, serial needs a protocol to go by in order to work efficiently.

**Comment by MichaelWallace30** [comment]
Yeah im not 100% but typically its one byte at a time with a checksum.

**Comment by CheezBoiger** [comment]
Can we use the common CRC pattern for the checksum?

**Comment by MichaelWallace30** [comment]
Ill look it up

**Comment by MichaelWallace30** [comment]
We can use crc but its more complex than we need.
