### ISSUE TITLE
Serial connection is slow and looses data

### ISSUE THREAD

**Issue by MichaelWallace30** [MichaelWallace30/CommProtocol#15]
Did you change serial some how? Its not working right at all. Test it out on linux and see if have the same issues. Every other message is unknown packet. I don't understand why its so slow.

**Comment by MichaelWallace30** [comment]
There is also a window error on serial, but I will fix that later. It just string miss handling.

**Comment by MichaelWallace30** [comment]
The problem isn't the serial code it self. I think its incorrectly parsing the data. I need to check some more.

**Comment by MichaelWallace30** [comment]
I don't want to parse one byte at a time because I read its slower, but I need to research the issue. I think the crc32 is working though.

**Comment by CheezBoiger** [comment]
Hmm. Let me check it out.

**Comment by MichaelWallace30** [comment]
Your good i know what i need to do.

**Comment by MichaelWallace30** [comment]
Im going to fix it and clean up serial. I need to run tests than ill push.

**Comment by CheezBoiger** [comment]
The error is not the parser, but something is definitely wrong with the serial protocol. It's not sending the packet at all.

**Comment by CheezBoiger** [comment]
the "Unknown Packet Received" is illogical of me, because it checks if the packet is null, but doesn't take into account that nothing was received.

**Comment by MichaelWallace30** [comment]
Give me a day to work on it.

**Comment by MichaelWallace30** [comment]
Im 90% sure i know the problem.

**Comment by CheezBoiger** [comment]
I realized for me, My serial port is not working.

**Comment by CheezBoiger** [comment]
oh i know why

**Comment by MichaelWallace30** [comment]
Windows is broken i need to fix it. Its the strcat//////.//

**Comment by CheezBoiger** [comment]
you sure?

**Comment by CheezBoiger** [comment]
lol, it's appending it...

**Comment by MichaelWallace30** [comment]
Shhh dont tell any one its embarrassing.

**Comment by CheezBoiger** [comment]
Secret is safe with me... (snickers*)

**Comment by CheezBoiger** [comment]
I recommend using sprintf

**Comment by CheezBoiger** [comment]
actually it wouldn't matter, because you still need a temp i believe.

**Comment by MichaelWallace30** [comment]
Yeah i had it working but i changed it for some reason. Ill just look up the old commit.

**Comment by CheezBoiger** [comment]
yea it works now. The Packet is being read.

**Comment by CheezBoiger** [comment]
go ahead and push the fix and ill pull it to my branch
