### ISSUE TITLE
Packet Manager unknown packets with data length 0

### ISSUE THREAD

**Issue by MichaelWallace30** [MichaelWallace30/CommProtocol#16]
The send and receive com link layer will return true or false if the desired network layer sends and read properly. I added serial to return false if the packet is zero, but I don't think the packet manager is checking any of this. 

The packet manager thinks a packet of length zero is an unknown packet, which is fine as long as the packets not being stored as an orphan. If you can look to make sure that would be great.

You can see this on the serial example when no data is read.

**Comment by CheezBoiger** [comment]
This problem was resolved in my branch.
