### ISSUE TITLE
Cleaning/Reorganizing connections.

### ISSUE THREAD

**Issue by CheezBoiger** [MichaelWallace30/CommProtocol#17]
Did you say you wanted more than one connection for the same CommsLink? Like if you set up UDP, you can have multiple UDP connections?

**Comment by CheezBoiger** [comment]
If that's the case, we need to make a New file called SerialLink, because Our Serial class only supports one connection at a time. I'll take care of it once you finish the Serial stuff.

**Comment by CheezBoiger** [comment]
Actually I have to do the same thing for UDP as well, so I'll need to create a separate file for that as well.

**Comment by CheezBoiger** [comment]
I will need your OK to start working on the network directory, because I'm going to be changing filenames, which will cause some crazy conflicts if you are still working in there.

**Comment by MichaelWallace30** [comment]
Its not that important. You can implement it if you want i was going to leave it out. Most situations wont need more than one connection besides gcs.

**Comment by CheezBoiger** [comment]
Nonway josie. This library gunna support swarm communication too

**Comment by CheezBoiger** [comment]
Dont worry about the reorganization. Ill take care of it

**Comment by CheezBoiger** [comment]
This is an open source library mang. It's gunna do more than just one connection

**Comment by MichaelWallace30** [comment]
I have to work on QT stuff for the decawave project so you can reorganize what ever you want just let me know when you are done so I don't break it.

**Comment by CheezBoiger** [comment]
Will do cap'in

**Comment by CheezBoiger** [comment]
I'lk close this issue when its done
