### ISSUE TITLE
Class naming convention for csharp wrappers.

### ISSUE THREAD

**Issue by MichaelWallace30** [MichaelWallace30/CommProtocol#20]
Just make one we have too many different naming going on. The simplest is to add a capital C in front of every thing.

**Comment by CheezBoiger** [comment]
Oops yea sorry, i have a naming convention we go by with C#.

**Comment by CheezBoiger** [comment]
I'll make one right now

**Comment by CheezBoiger** [comment]
I have added the naming convention in the last push now.
