### ISSUE TITLE
CommProtocol Manual

### ISSUE THREAD

**Issue by CheezBoiger** [MichaelWallace30/CommProtocol#22]
I'm going to start on the CommProtocol manual.

**Comment by MichaelWallace30** [comment]
This is different than api manual correct?

**Comment by CheezBoiger** [comment]
This is the same. Because the manual will cover Beginner, intermediate, and advanced API calls to use the library.

**Comment by CheezBoiger** [comment]
You want to split up the APIs from the manual?

**Comment by MichaelWallace30** [comment]
Thats fine you need to show me how you want it.

**Comment by MichaelWallace30** [comment]
It can all still be together it doesn't matter to me. Did you test c# to c++?

**Comment by CheezBoiger** [comment]
oo, i should test that.

**Comment by CheezBoiger** [comment]
I'll let you know the results soon

**Comment by MichaelWallace30** [comment]
I got basic data through udp didn't try the linking of a call back.

**Comment by CheezBoiger** [comment]
Oh you tried it?

**Comment by MichaelWallace30** [comment]
Yeah but I don't know how to make the call back error_t wasn't coming up.

I was going to add clr to cmake, but cmake has it already. Visual studio doesn't list clr is it really compiling as clr?

**Comment by CheezBoiger** [comment]
Clr does get added to cmake, it's a bug for some reason. Visual studio doesn't show in the linker, but if you look at the commands in command line arguments, in compiler, it shoupd be there.

**Comment by CheezBoiger** [comment]
I'll what the problem is with callback, i havent tried it yet though.

**Comment by CheezBoiger** [comment]
I know why error_t isn't popping up, it needs to be written as 
```C#
using error_t = System.Int32;
```
You don't necessarily need to pass error_t type, just return an int for your callback.

**Comment by CheezBoiger** [comment]
The callbacks work!

**Comment by CheezBoiger** [comment]
You need to pull from my branch again because There was a problem with the ABSPacket. It should work find now.

**Comment by MichaelWallace30** [comment]
Huzzah

**Comment by CheezBoiger** [comment]
Was Protonet able to integrate C# and C++ nodes? heh 🎱
