### ISSUE TITLE
Encryption missing definitions

### ISSUE THREAD

**Issue by CheezBoiger** [MichaelWallace30/CommProtocol#23]
The CryptoPP files are missing definitions for a few static arrays, I can't seem to compile the library without those definitions. They are (from rijndael.h) Se, Sd, and rcon, as well as (from des.h) Spbox. 

I'm not sure how the encryption stuff works, or what files are needed, but these arrays are not letting the encryption compile for some reason.

**Comment by MichaelWallace30** [comment]
Is this linux?

**Comment by MichaelWallace30** [comment]
My g++ isn't listing the missing files how did you get it to display whats missing?

**Comment by MichaelWallace30** [comment]
Im confused I added the compiler command -MM to print needed header files and it just compiles now....

**Comment by CheezBoiger** [comment]
Weird... I got errors on visual studio...

**Comment by MichaelWallace30** [comment]
oh ill look I can compile the example for cmake it can't find the library.

**Comment by MichaelWallace30** [comment]
Im not getting any errors on vs 2013 or 2015

**Comment by MichaelWallace30** [comment]
I can dump all the files if you want and try that.

**Comment by CheezBoiger** [comment]
Where you able to compile the shared library?

**Comment by MichaelWallace30** [comment]
only the static come up how do cmake the shared one?

**Comment by CheezBoiger** [comment]
The static library compiles, but the shared doesnt for some reason

**Comment by MichaelWallace30** [comment]
i SEE IT

**Comment by MichaelWallace30** [comment]
let me test it out

**Comment by CheezBoiger** [comment]
lulz.

**Comment by CheezBoiger** [comment]
Yea, the static lib compiles, i don't know why shared doesn't for some reason.

**Comment by CheezBoiger** [comment]
Were you able to repeat the error?

**Comment by MichaelWallace30** [comment]
Yeah i need more time I cant figure it out.

**Comment by MichaelWallace30** [comment]
If i include all the files it complains about a rnd .adm file

**Comment by MichaelWallace30** [comment]
Asm file

**Comment by CheezBoiger** [comment]
I don't mind if we need to compile CryptoPP separately and link them after.

**Comment by CheezBoiger** [comment]
We might just do that for Xbee as well.

**Comment by MichaelWallace30** [comment]
Its just a setting on visual studio. I can compile it with the gives solution file.

**Comment by CheezBoiger** [comment]
We might just compile it separately.

**Comment by MichaelWallace30** [comment]
I would perfer not to. Give me a week to figure it out im getting close. Just remove the cmake stuff if you need to compile.

**Comment by CheezBoiger** [comment]
Yea, it works fine with static, just dont compile the lib as shared for now. Right now im trying to figure out why CommProtoExe isnt working on linux though. It works fine for windows

**Comment by CheezBoiger** [comment]
It works but the linker is ignoring it for some reason...

**Comment by CheezBoiger** [comment]
-MM is causing issues for me man... It's preventing linkage of subdirectories for CommProtoExe and Visionary. When I took it off, it worked fine and linked perfectly.

**Comment by CheezBoiger** [comment]
inside strciphr.h:line 614:
```C++
#ifdef CRYPTOPP_MANUALLY_INSTANTIATE_TEMPLATES
#include "strciphr.cpp"
#endif
```
This...is...fucking...retarded....

Who hires people to do this...include a source file into a header file...

**Comment by CheezBoiger** [comment]
Did these devs test this crypto++ lib in linux before releasing it? I can't compile it on g++...

**Comment by MichaelWallace30** [comment]
So the problem with our cmake and cryptopp is -std c++ 11 flag. They must have changed rules because thats whats causing the issue.

**Comment by CheezBoiger** [comment]
It should be fixef

**Comment by MichaelWallace30** [comment]
Hey not sure what you did, but I found one problem.
//old
sets all files to c++11
//new sets only needed file to c++11
add_compile_options(-std=c++11 -pthread)

**Comment by MichaelWallace30** [comment]
this is cmake version 3.0 above which we are forcing any way I would change it to this.

**Comment by CheezBoiger** [comment]
This is a much better command instead of cxx flags

**Comment by CheezBoiger** [comment]
If using that, we up the cmake minimum to 3.0?

**Comment by MichaelWallace30** [comment]
add_compile_options require version 3.0 and above

the other way is for below version 3.0

**Comment by CheezBoiger** [comment]
We don't have to force the minimum required cmake version to be 3.0. We can check if the cmake version is greater than 3.0, and then add the command.

**Comment by MichaelWallace30** [comment]
True but I would just force it they can update cmake real easy.

**Comment by CheezBoiger** [comment]
true lulz.

**Comment by CheezBoiger** [comment]
set compiler options is giving me more trouble than they're worth...

**Comment by MichaelWallace30** [comment]
The add_compile_options is throwing errors?

**Comment by CheezBoiger** [comment]
it's not linking pthreads

**Comment by MichaelWallace30** [comment]
Ok if you can just do std c++11 with add and pthread with the old.

**Comment by MichaelWallace30** [comment]
Did you read thus?
http://stackoverflow.com/questions/26343176/why-cmake-does-not-seem-to-apply-pthread-using-add-compile-options-command

**Comment by MichaelWallace30** [comment]
Saus -pthread is a linker option std=c++11 is a compile option.

**Comment by CheezBoiger** [comment]
ugh, add_compile_options is strictly compiler... that's ridiculous...

**Comment by CheezBoiger** [comment]
ok, it's fixed, ima push it

**Comment by MichaelWallace30** [comment]
What happened I cant compile on linux for dev-mg its the same issue I thought we fixed?

**Comment by MichaelWallace30** [comment]
never mind it built the second time
