### ISSUE TITLE
release debug visual studio

### ISSUE THREAD

**Issue by MichaelWallace30** [MichaelWallace30/CommProtocol#25]
If you already know can you add visual studio debug release mode option so I can set the dependencies directory. If you don't know Ill keep researching the best way to do this.

**Comment by CheezBoiger** [comment]
Adding debug/release for CMake?

**Comment by CheezBoiger** [comment]
I'll add them in as options.

**Comment by CheezBoiger** [comment]
Unfortunately im reading alot of issues stating that you can't set debug or release mode through cmake with visual studio.

**Comment by MichaelWallace30** [comment]
Ok I found some stuff, but just ignore it for now and Ill decide what to do with in a week.
