### ISSUE TITLE
Float Values are not received!

### ISSUE THREAD

**Issue by CheezBoiger** [MichaelWallace30/CommProtocol#26]
I don't think float values are being properly serialized.

**Comment by CheezBoiger** [comment]
Nevermind they are. There is situation with Csharp receiving it though.

**Comment by CheezBoiger** [comment]
Oh I'm an idiot. Sorry It's my mistake... The Library is fine. I did a stupid in the application.

**Comment by MichaelWallace30** [comment]
One of the reasons I am using std reverse is because I had problems with floating point numbers when I switched the endianess.

**Comment by CheezBoiger** [comment]
It's alright, the library works fine.

**Comment by MichaelWallace30** [comment]
Yeah just justifying my my decision.

**Comment by CheezBoiger** [comment]
we'll. looks like the jury finds you innocent. No need for the executioner. Good thing I'm not judge Dredd.
