### ISSUE TITLE
xbee error code

### ISSUE THREAD

**Issue by MichaelWallace30** [MichaelWallace30/CommProtocol#27]
22
Test complete!
Waiting for driver to query Xbee device...
Finished device xbee query...

> Query status failed... Error code=-138

failed to close serial port=3
Home xbee failed to initialize!
Init connection succeeded: false
Could not find node id in range!
Connected to address: false
Sleeping...

Press any key to continue . . .

**Comment by CheezBoiger** [comment]
how am i supposed to repeat this error if i don't have the xbees....

**Comment by CheezBoiger** [comment]
Also, what is the example you provided?

**Comment by MichaelWallace30** [comment]
XBEE_COMMAND_LIST_TIMEOUT = -ETIMEDOUT,

You should have taken them two today. Ill give you them on Wednesday, Thursday, or Friday

**Comment by MichaelWallace30** [comment]
`  std::cout << "Test complete!" << std::endl;
  std::cout << "Init connection succeeded: "
	  << std::boolalpha
	  << comm1.InitConnection(ZIGBEE_LINK, "COM12", NULL, 9600)
            << std::endl;
  std::cout << "Connected to address: "
            << std::boolalpha
            << comm1.AddAddress(2, "0013A20040917A31")
            << std::endl;`

**Comment by MichaelWallace30** [comment]
This is a different xbee the comport was changed

**Comment by MichaelWallace30** [comment]
It fails InitConnection

**Comment by MichaelWallace30** [comment]
Are you on campus on Wednesday?

**Comment by CheezBoiger** [comment]
im gunna need those xbees thursday, I pretty coded blind with this.

**Comment by CheezBoiger** [comment]
I don't have class Wednesday lul

**Comment by MichaelWallace30** [comment]
Yeah just wanted the error code, but I found it.

**Comment by CheezBoiger** [comment]
also be sure to set the xbee baudrate to 11520, 9600 is not sufficient

**Comment by MichaelWallace30** [comment]
Ill double check the xbee settings

**Comment by CheezBoiger** [comment]
Look through the debugger, and see what goes on inside initConnection

**Comment by MichaelWallace30** [comment]
I did it just queries the xbee and returns the -128

this opens
`  // open the serial port to xbee.
  status = xbee_ser_open(&serial, baudrate);`

this parts skips the if and goes into else which inside the do while loop status goes to -128
`    if (xbee_dev_init(&device, &serial, NULL, NULL)) {
      COMMS_DEBUG("Xbee failed to initialize.\n");
    } else {
      xbee_wpan_init(&device, sample_endpoints);
      // Add node discover handler.
      xbee_disc_add_node_id_handler(&device, &NodeDiscovered);
      xbee_cmd_init_device(&device);
      COMMS_DEBUG("Waiting for driver to query Xbee device...\n");
      do {
        xbee_dev_tick(&device);
        status = xbee_cmd_query_status(&device);
      } while (status == -EBUSY);`

**Comment by MichaelWallace30** [comment]
Sorry xbee_atcmd.c

**Comment by CheezBoiger** [comment]
It's an errno number, means key has been revoked. I dont know what that means....

**Comment by MichaelWallace30** [comment]
this is the error 

`XBEE_COMMAND_LIST_TIMEOUT = -ETIMEDOUT`

**Comment by MichaelWallace30** [comment]
Don't worry about it right now just use this for reference if you need to when you test it. I was in a rush I should have gave you two xbees.

**Comment by MichaelWallace30** [comment]
yeah the baud rate is 57600 I tried that

**Comment by CheezBoiger** [comment]
I'll have to wait until I get the xbees. This library blows chunks

**Comment by CheezBoiger** [comment]
Where you able to get info on the xbees through the dev init function at least?

**Comment by CheezBoiger** [comment]
Yea, ETIMEOUT is an errno number
It's defined in Microsoft header API errno.h
```C++
//
// errno.h
//
//      Copyright (c) Microsoft Corporation. All rights reserved.
//
// System error numbers for use with errno and errno_t.
//
#pragma once
#define _INC_ERRNO

#include <corecrt.h>

_CRT_BEGIN_C_HEADER



_ACRTIMP extern int* __cdecl _errno(void);
#define errno (*_errno())

_ACRTIMP errno_t __cdecl _set_errno(_In_ int _Value);
_ACRTIMP errno_t __cdecl _get_errno(_Out_ int* _Value);



_ACRTIMP unsigned long* __cdecl __doserrno(void);
#define _doserrno (*__doserrno())

_ACRTIMP errno_t __cdecl _set_doserrno(_In_ unsigned long _Value);
_ACRTIMP errno_t __cdecl _get_doserrno(_Out_ unsigned long * _Value);



// Error codes
#define EPERM           1
#define ENOENT          2
#define ESRCH           3
#define EINTR           4
#define EIO             5
#define ENXIO           6
#define E2BIG           7
#define ENOEXEC         8
#define EBADF           9
#define ECHILD          10
#define EAGAIN          11
#define ENOMEM          12
#define EACCES          13
#define EFAULT          14
#define EBUSY           16
#define EEXIST          17
#define EXDEV           18
#define ENODEV          19
#define ENOTDIR         20
#define EISDIR          21
#define ENFILE          23
#define EMFILE          24
#define ENOTTY          25
#define EFBIG           27
#define ENOSPC          28
#define ESPIPE          29
#define EROFS           30
#define EMLINK          31
#define EPIPE           32
#define EDOM            33
#define EDEADLK         36
#define ENAMETOOLONG    38
#define ENOLCK          39
#define ENOSYS          40
#define ENOTEMPTY       41

// Error codes used in the Secure CRT functions
#ifndef RC_INVOKED
    #define _SECURECRT_ERRCODE_VALUES_DEFINED
    #define EINVAL          22
    #define ERANGE          34
    #define EILSEQ          42
    #define STRUNCATE       80
#endif

// Support EDEADLOCK for compatibility with older Microsoft C versions
#define EDEADLOCK       EDEADLK

// POSIX Supplement
#ifndef _CRT_NO_POSIX_ERROR_CODES
    #define EADDRINUSE      100
    #define EADDRNOTAVAIL   101
    #define EAFNOSUPPORT    102
    #define EALREADY        103
    #define EBADMSG         104
    #define ECANCELED       105
    #define ECONNABORTED    106
    #define ECONNREFUSED    107
    #define ECONNRESET      108
    #define EDESTADDRREQ    109
    #define EHOSTUNREACH    110
    #define EIDRM           111
    #define EINPROGRESS     112
    #define EISCONN         113
    #define ELOOP           114
    #define EMSGSIZE        115
    #define ENETDOWN        116
    #define ENETRESET       117
    #define ENETUNREACH     118
    #define ENOBUFS         119
    #define ENODATA         120
    #define ENOLINK         121
    #define ENOMSG          122
    #define ENOPROTOOPT     123
    #define ENOSR           124
    #define ENOSTR          125
    #define ENOTCONN        126
    #define ENOTRECOVERABLE 127
    #define ENOTSOCK        128
    #define ENOTSUP         129
    #define EOPNOTSUPP      130
    #define EOTHER          131
    #define EOVERFLOW       132
    #define EOWNERDEAD      133
    #define EPROTO          134
    #define EPROTONOSUPPORT 135
    #define EPROTOTYPE      136
    #define ETIME           137
    #define ETIMEDOUT       138
    #define ETXTBSY         139
    #define EWOULDBLOCK     140
#endif // _CRT_NO_POSIX_ERROR_CODES



_CRT_END_C_HEADER

```

**Comment by CheezBoiger** [comment]
Don't listen to my texts! Anyway, you should have at least gotten this message
```
22
Test complete!
Failed to open serial port=12
```
For some reason you tried opening port 3...

**Comment by MichaelWallace30** [comment]
I changed the port. I had two sheets one on 3 and one on 12. I got past that. The serial port opens.

**Comment by CheezBoiger** [comment]
So then why is it failing to close port 3 if you are opening port 12?

**Comment by CheezBoiger** [comment]
Oh you are testing both xbees on the same program...

**Comment by MichaelWallace30** [comment]
It's two different tests the comports and baudrate was correct I assure you.

**Comment by CheezBoiger** [comment]
The TimeOut is not a software issue though... it's hardware i think

**Comment by CheezBoiger** [comment]
It is only querying the device, but it can't possibly be the code's reason.

**Comment by CheezBoiger** [comment]
What's the API set on the xbees?

**Comment by CheezBoiger** [comment]
I think the code im using is set for "AT mode" and not "API mode"

**Comment by CheezBoiger** [comment]
OMG, I think this library is only set to work with AT mode xbees, not API mode xbees

**Comment by CheezBoiger** [comment]
Yea I followed the example of setting up the network for xbees in AT mode, not Point-to-Point. For some reason, the library doesn't show you a sample on how to do that. They don't have proper documentation on how to set one up, so damn. It appears to set up point-to-point I need to use sxa.h and sxa_socket.h...

**Comment by MichaelWallace30** [comment]
Uh you dont need all of those file to use AT mode just need a serial connection.

**Comment by MichaelWallace30** [comment]
I'll test AT, but I assume you know that's not what we need.

**Comment by MichaelWallace30** [comment]
I put it in AT mode and the same thing.

**Comment by MichaelWallace30** [comment]
So the sxa.h file looks good says "Simplified XBee API"

If that fails we should think about switching back to Atties.  Ill give it two weeks due to the complexity of AnsiC XBee Library.

**Comment by CheezBoiger** [comment]
I really cant do anything with thise bees

**Comment by CheezBoiger** [comment]
It has to be the d hardware...

**Comment by CheezBoiger** [comment]
The library wont let you use sxa because it's only compatible with rabbit.

**Comment by MichaelWallace30** [comment]
Well ill start to look at atties make file. You can stuff out Thursday.

**Comment by CheezBoiger** [comment]
Yea, switch the xbee library to attie.

**Comment by MichaelWallace30** [comment]
I put up a working libxbee3 with cmake for windows. Going to need more work though.
