### ISSUE TITLE
Libxbee3 xbee

### ISSUE THREAD

**Issue by MichaelWallace30** [MichaelWallace30/CommProtocol#28]
So the problem is the libxbee and xbee wont send data bigger than 72 bytes....

**Comment by CheezBoiger** [comment]
We can break it up

**Comment by CheezBoiger** [comment]
Im at schoo right now

**Comment by MichaelWallace30** [comment]
Ok I have home work than I need to go to school. Im going to see if this is a mistake or there's a reason this is happening.

**Comment by CheezBoiger** [comment]
Its not bad. Udp and tcp also have a limit, so breaking it up is probably faster than sending all at once

**Comment by MichaelWallace30** [comment]
http://knowledge.digi.com/articles/Knowledge_Base_Article/Sending-data-through-an-802-15-4-network-latency-timing

The 802.15.4 PHY layer allows a maximum 127 bytes per packet, including payload. Due to the size of the packet header, XBee Series 1 modules can send a maximum payload of 100 bytes. XBee Series 2 modules, which utilize more header bytes for ZigBee mesh networking, can send a maximum payload of 72 bytes.

**Comment by CheezBoiger** [comment]
Not too bado

**Comment by MichaelWallace30** [comment]
I prefer we implement the packet sequence only on the comxbee.ccp. The simplest idea would  be add a new header with two bytes one being sequence number second being number of sequences total. This would repeat until all sequences are done then return data to xbeeLinks. There is no packet number on the xbee api, but there is a frame if which is not the same. The xbee api also has a check sum so we wouldn't need to add a check sum for our packets. Lastly if for some reason the newly formed data from all the sequence packets is corrupt the encryption should throw it out as garbage and we wouldn't need a new check sum, but I could be wrong and maybe we need a crc32 check sum for the whole message in commsLink. Would like to hear other ideas to see if you have a better solution. I just don't want to force all communication links to a packet size of 72 for no good reason.

**Comment by CheezBoiger** [comment]
Well thats not what i want either, forcing packets to be of less than size 72 is boring. If the packet size is greater, split the packet up evenly as possible, set a sequence as you said, that the packet is split and will need to be continously read. Does atties code have a more data enum state when reading? Im sure the xbees take care of this problem regardless, so we need not worry. Tcp and udp handle these problems without us needing to worry about the packet limit, it actually uses an algorithm to breakup packets. I dont think we really need to worry about this unless you tested and confirmed that atties code isnt breaking up the packet and handling this issue.

**Comment by CheezBoiger** [comment]
In most cases if packets are beyond the limit, the protocol will just split it up and send one part of the packet, but its just up the programmer how the distribution is going to wait before reading. If youve done network programming in java, its ugly you have to loop over the buffer to make sure you sent all the data, and the receiver would need to be waiting until there is a terminal sequence or a timeout. In this case, just using the terminal seqence in our parser is good enough.

**Comment by CheezBoiger** [comment]
This is where your elite h@ck0rz skillz com 2 da test, lul

**Comment by MichaelWallace30** [comment]
They idea of the using our length is a good idea, but we would need the terminal start and end. Even though more header data would create overhead it would separate comms header from commsxbee. Probably going to focus on school work than work on this.

**Comment by CheezBoiger** [comment]
Yea, for now it's not too bad. We hit 50 bytes with our test.

**Comment by MichaelWallace30** [comment]
Our test data was 78 bytes

**Comment by CheezBoiger** [comment]
whoa, really? damn.

**Comment by CheezBoiger** [comment]
oh i remember now, i made the string larger

**Comment by MichaelWallace30** [comment]
IP packets use this method.

3 bits for flags and 13 bits for offset.

1 bit not used
2 bit indicates fragmented data
3 bit indicates more fragmented data 

4 - 16 bits are the offset of the data

**Comment by CheezBoiger** [comment]
yarp, That's why you have to read the packet and check if there isn't any more data in the buffer, or if the packet is fragmented.

**Comment by CheezBoiger** [comment]
How does Zigbee handle the packet splitting?

**Comment by MichaelWallace30** [comment]
I don't think it does.

**Comment by MichaelWallace30** [comment]
http://knowledge.digi.com/articles/Knowledge_Base_Article/Calculating-the-Checksum-of-an-API-Packet

**Comment by MichaelWallace30** [comment]
API Frame ID to my understanding it the type of AT frame like tx, rx ,ect.

I went with seq / maxSeq because
255 * 70 = 17850 bytes offset

while 14 bits is
16383 bytes offset
