### ISSUE TITLE
abstractPacket.h noexcept

### ISSUE THREAD

**Issue by MichaelWallace30** [MichaelWallace30/CommProtocol#31]
Visual Studio 2013
Error	375	error C3646: 'noexcept' : unknown override specifier

Looks like this is C++11 feature missing from vs 2013

**Comment by CheezBoiger** [comment]
oh I forgot it's a 14 feature.

**Comment by Jester565** [comment]
http://stackoverflow.com/questions/18387640/how-to-deal-with-noexcept-in-visual-studio
Solution... I think

**Comment by CheezBoiger** [comment]
Yea should more of a macro instead

**Comment by CheezBoiger** [comment]
fixed.
