### ISSUE TITLE
Winsock2

### ISSUE THREAD

**Issue by MichaelWallace30** [MichaelWallace30/CommProtocol#45]
Having issues with header files in GCS which is due to Winsock2 and I assume after the TCP code. Im trying to narrow it down. Im using the NGCP branch which is behind this repo. If you know a fix let me know. It only occurs in QT

**Comment by MichaelWallace30** [comment]
winsock redefinition different linkage

**Comment by Jester565** [comment]
[This StackOverflow post](http://stackoverflow.com/questions/1742273/qt-creator-with-winsocks-ws2-32) says that you have to actually include the winsock library in the qmake.

**Comment by MichaelWallace30** [comment]
Having issues with my toolset is the issue i think but ill try it

**Comment by Jester565** [comment]
I'll see if I can get it working on my old QT. But it might take me a while cause I actually have to learn how to use this IDE first.

**Comment by MichaelWallace30** [comment]
Its only happening on v120 and v140. I have it on another computer you dont need to waste a bunch of time.

**Comment by MichaelWallace30** [comment]
Tried including it in QT .pro still didn't work

**Comment by Jester565** [comment]
Ummm... There is also the issue of including winsock2 after windows.h [This post](http://stackoverflow.com/questions/5971332/redefinition-errors-in-winsock2-h) offers a solution

**Comment by MichaelWallace30** [comment]
Must be some thing else the old repo with has winsock2 in it

**Comment by Jester565** [comment]
It is included in socket-config.h.

**Comment by MichaelWallace30** [comment]
The git commit "tcplink is functional in standard use case" on march 3rd starts the erros

**Comment by Jester565** [comment]
Get rid of the WinSock2 include in socket-config. See if it works then. Cause I include comm_mutex (which includes windows.h and then socket-config.h, which includes winsock2

**Comment by MichaelWallace30** [comment]
I tried changing the order. I did a hard reset unfortunately on NGCP. I need to move on, but this still needs to be fixed. GCS uses QT 5.6.2 msvc 2013 if you want to play with it at some point.

**Comment by Jester565** [comment]
So many compilers... I'll have to configure my QT to perform these tests on my own.  Sorry about that.

**Comment by MichaelWallace30** [comment]
Not a big deal our QA testing is lacking. Will just remote Mario to QA.

**Comment by Jester565** [comment]
Were you only getting this problem in the GCS project?  I ran the TCPTest project fine with VS2013 64 bit in qt creator 5.8.0 and did not get any errors.  I'm trying to get GCS running but I do not have the arcgis library. I've done quite a bit of searching.  Is there a guide to how to link that to qt?

**Comment by MichaelWallace30** [comment]
Ok you need msvc2013 QT
Download arcgis sdk 10.26 Q
- make sure you check c++ and qml on install
- post install qt creator & msvc 2013 debug

**Comment by MichaelWallace30** [comment]
GCS might be including network conflicts and its not a QT issue. Pull my gcs no ngcp. Just replace Commproto folder on gcs and add build folder. I can help you Friday.

**Comment by Jester565** [comment]
YES!  I finally got it working!  I'm going to create a google doc on how to set the project up. That was ridiculous.  But I'm getting the error now.

**Comment by MichaelWallace30** [comment]
Took me like six hours

**Comment by CheezBoiger** [comment]
Lulz. Get ready to fall down the gcs rabbit hole...

**Comment by Jester565** [comment]
Fall down? Is this not the bottom?

**Comment by CheezBoiger** [comment]
Far from it. You've only made it passed the clouds, therein lies the unknown, backward, often confusing, mountains that is gcs qt application

**Comment by MichaelWallace30** [comment]
Alex in gcs. Pro there is a line "console serial network" check removing network

**Comment by Jester565** [comment]
Wait, did that fix it?

**Comment by Jester565** [comment]
That didn't fix it

**Comment by MichaelWallace30** [comment]
Ok just didnt check it

**Comment by CheezBoiger** [comment]
Repent. The end is nye, gcs will get a hold of you too alex, dont let it!!! A life taker and heart breaker! Wallace pulled you down! Its a trap!

**Comment by Jester565** [comment]
*Insert Admiral Ackbar here*

**Comment by Jester565** [comment]
What's probably happening is that one of GCS's 50 gb worth or libraries is including winsock.h NOT winsock2.h.  I have no idea what to do about this.  The windows library sucks so much.

**Comment by Jester565** [comment]
OK, I have an obvious yet difficult solution.  If socket-config.h is only in cpp files GCS will compile. So I have to get forward declaring now.

**Comment by Jester565** [comment]
Fixed issue with commit d390f1b900031bde56284ae8f9677e6ad85a893b.  I will be working on a document on how to install GCS [here](https://docs.google.com/document/d/1-_i-8Xuv7vC-JKqS8MSC5HfYDe7tJruElEcmgfDNEQo/edit?usp=sharing).

**Comment by MichaelWallace30** [comment]
Ok you should push the document to ngcp/gcs after they accept my pull request.
