### ISSUE TITLE
C# Implementation

### ISSUE THREAD

**Issue by CheezBoiger** [MichaelWallace30/CommProtocol#5]
We will need to work on C# interface soon, but not now.

**Comment by MichaelWallace30** [comment]
So I know you wanted to write the comms in c#, but do you want them to compile comms again or just use the inherited node "comms" inside the project? That would be three compiles for a c# version.

**Comment by CheezBoiger** [comment]
We can write Comms in the C++CLI library, that why they don't have to compile from CommProto->CommWrapper->CommSharp. At this point, CCommsNode can be used both in C++CLI and C#, so we can cut the compile time if we implement CCommNode within C++CLI.
